Задание 6, чанк 64 даёт наилучшую скорость.
AndreyPreobrazhensky/Practicum-v-ponedelnik pull request #8
Opened 2024-11-06 20:53 UTC by AndreyPreobrazhensky

На полюсе не запускается программа с созданием массива длины 1000000. Для размера 262144 инта я успешно обогнал qsort

2024-11-06 20:55 UTC, dimlichmanov requested changes
.

2024-11-06 20:55 UTC, dimlichmanov commented on sortingm.c
> +	int m[N], n[N];
А это норм у вас на 1000000 работает?

2024-11-06 21:00 UTC, AndreyPreobrazhensky commented on sortingm.c
> +	int m[N], n[N];
Да, память на 1000000 байт выделяется, нормально. Просто Polus пишет что не может выделить достаточное количество ресурсов для выполнения программы.

2024-11-06 21:01 UTC, dimlichmanov commented on sortingm.c
> +	int m[N], n[N];
Скиньте вывод

2024-11-06 21:07 UTC, AndreyPreobrazhensky commented on sortingm.c
> +	int m[N], n[N];
Извиняюсь, максимально 524288 работает локально, на полюсе тоже писал что недостаточно ресурсов. Я написал, что выделяет потому что в одной из предыдущих программ по один  миллион массив успешно выделялся.

2024-11-07 19:18 UTC, dimlichmanov requested changes
.

2024-11-07 19:18 UTC, dimlichmanov commented on sortingm.c
> +	int m[N], n[N];
А вы принципиально хотите на стеке всё решить?

2024-11-07 19:21 UTC, AndreyPreobrazhensky commented on sortingm.c
> +	int m[N], n[N];
Нет, можно и через динамическую память сделать, думаю нет принципиальной разницы. 
С ростом N алгоритм лучше только работает, на миллионе тоже должен обогнать, наверное.

2024-11-07 19:27 UTC, dimlichmanov commented on sortingm.c
> +	int m[N], n[N];
Ну, наверное. Это и жду в отчёте)

2024-11-07 19:27 UTC, dimlichmanov requested changes
.

2024-11-09 10:48 UTC, dimlichmanov requested changes
![изображение](https://github.com/user-attachments/assets/d4ec392b-0670-49a9-961f-ed1f266a881a)

2024-11-09 11:22 UTC, dimlichmanov approved these changes

2024-11-10 17:12 UTC, closed without merging