Программа
AndreyPreobrazhensky/Practicum-v-ponedelnik pull request #9
Opened 2024-11-09 19:49 UTC by AndreyPreobrazhensky

Программа работает локально, однако на полюсе виснет при первой попытке сделать send - recieve, фото с параметрами запусков и содержимым файла ошибки прикрепляю, сразу напишу что на одном потоке программа не работает, буду дорабатывать. Главное - не понимаю почему не работает send - recieve.  Втрой вопрос - на одном из скриншотов видно, что несмотря на указание явно OMP_NUM_THREADS=2, написано что программа запустилась с переменной окружения = 1, наверное это как-то связано.

2024-11-09 20:44 UTC, dimlichmanov commented
Так, я посмотрю чуть позже, но основное замечание - забудьте про OMP_NUM_THREADS= при постановке задач MPI, в которых не используются доп.потоки. (1 поток на процесс)

2024-11-09 20:44 UTC, dimlichmanov commented
Это будет у нас чуть позже

2024-11-10 09:26 UTC, dimlichmanov commented
У вас такая блокировка возникает на размере 2048, верно?
Попробуйте запустить на 256, должно с той же последовательностью вызовов MPI отработать успешно.

Вкратце - MPI в таких передачах, когда два процесса обмениваются друг с другом, может под капотом MPI_Send ставить не MPI_Bsend, как в маленьких сообщениях, а MPI_Ssend (синхронизованный, когда всё блокируется)

Как избежать этого и запустить на 2048 - смотрите последний пример с семинара.

2024-11-10 09:26 UTC, dimlichmanov requested changes
.

2024-11-10 17:21 UTC, AndreyPreobrazhensky commented
С предидущим разобрался, работает, теперь вот такая проблема:
Я пытаюсь откомпилировать с флагами из презентации.
mpicc -g -Wl,-rpath=/home/edu-cmc-sqi24-10/mpiP-3.5 -L /home/edu-cmc-sqi24-10/mpiP-3.5/ -lmpiP mpiprog.c
выдаёт cannot find -lmpiP. Пробовал компилировать как в домашней папке, так и непосредственно в папке /mpiP-3.5

В гайде написано, что можно не компилировать так, просто указать  LD_PRELOAD. В него записывается нужный файл, однако при компиляции выдаётся ошибка object cannot be preloaded, программа при этом отрабатывает, но отчёт по  mpiP не выдаёт. 

Правильно ли я указываю путь к библиотеке и что можно предпринять в данной ситуации? 
![photo_2024-11-10_20-21-36](https://github.com/user-attachments/assets/1333af06-40ed-4e42-974e-07b59efa10cd)

2024-11-10 17:50 UTC, dimlichmanov commented
1) Попробуйте собрать программу через ту же команду с чистой переменной окружения LD_PRELOAD=
(export LD_PRELOAD=) 
(после знака равенства ничего нет)
2) если не получится, попробуйте LD_PRELOAD сделать с полным путём к директории

Не получится никак, подойдите завтра.

2024-11-10 17:50 UTC, dimlichmanov requested changes
.

2024-12-08 07:08 UTC, closed without merging